[project]
name = "civ-python-2025"
version = "0.1.0"
description = "Charite institute of virology Berlin Python course 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.14.0",
    "polars>=1.32.3",
]
